Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/baron.py", line 20, in _parse
    return parser(tokens)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/grammator.py", line 695, in parse
    return parser.parse(iter(tokens))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/parser.py", line 168, in parse
    raise ParsingError(debug_output)
baron.parser.ParsingError: Error, got an unexpected token $end here:

 106         return conv(int(n/1000000)) + milioni[2] + conv(int(n%10000))
 107 
 108 print(conv(981008818))
 109 
 110     
 111 
 112     
 113 <---- here

The token $end should be one of those: ASSERT, AT, BACKQUOTE, BINARY, BINARY_RAW_STRING, BINARY_STRING, BREAK, CLASS, COMMENT, COMPLEX, CONTINUE, DEDENT, DEF, DEL, ENDL, ENDMARKER, EXEC, FLOAT, FLOAT_EXPONANT, FLOAT_EXPONANT_COMPLEX, FOR, FROM, GLOBAL, HEXA, IF, IMPORT, INT, LAMBDA, LEFT_BRACKET, LEFT_PARENTHESIS, LEFT_SQUARE_BRACKET, LONG, MINUS, NAME, NOT, OCTA, PASS, PLUS, PRINT, RAISE, RAW_STRING, RETURN, STRING, TILDE, TRY, UNICODE_RAW_STRING, UNICODE_STRING, WHILE, WITH, YIELD

It is not normal that you see this error, it means that Baron has failed to parse valid Python code. It would be kind if you can extract the snippet of your code that makes Baron fail and open a bug here: https://github.com/Psycojoker/baron/issues

Sorry for the inconvenience.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/cc.py", line 84, in <module>
    results=cc.evaluate(file)
  File "lib/cc.py", line 19, in evaluate
    red = redbaron.RedBaron(file.read())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/redbaron/redbaron.py", line 36, in __init__
    self.node_list = base_nodes.NodeList.from_fst(baron.parse(source_code), parent=self, on_attribute="root")
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/baron.py", line 66, in parse
    return _parse(tokens, print_function)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/baron.py", line 26, in _parse
    raise e
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/baron.py", line 24, in _parse
    return parser(tokens)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/grammator.py", line 695, in parse
    return parser.parse(iter(tokens))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/parser.py", line 168, in parse
    raise ParsingError(debug_output)
baron.parser.ParsingError: Error, got an unexpected token $end here:

 106         return conv(int(n/1000000)) + milioni[2] + conv(int(n%10000))
 107 
 108 print(conv(981008818))
 109 
 110     
 111 
 112     
 113 <---- here

The token $end should be one of those: ASSERT, AT, BACKQUOTE, BINARY, BINARY_RAW_STRING, BINARY_STRING, BREAK, CLASS, COMMENT, COMPLEX, CONTINUE, DEDENT, DEF, DEL, ENDL, ENDMARKER, EXEC, FLOAT, FLOAT_EXPONANT, FLOAT_EXPONANT_COMPLEX, FOR, FROM, GLOBAL, HEXA, IF, IMPORT, INT, LAMBDA, LEFT_BRACKET, LEFT_PARENTHESIS, LEFT_SQUARE_BRACKET, LONG, MINUS, NAME, NOT, OCTA, PASS, PLUS, RAISE, RAW_STRING, RETURN, STRING, TILDE, TRY, UNICODE_RAW_STRING, UNICODE_STRING, WHILE, WITH, YIELD

It is not normal that you see this error, it means that Baron has failed to parse valid Python code. It would be kind if you can extract the snippet of your code that makes Baron fail and open a bug here: https://github.com/Psycojoker/baron/issues

Sorry for the inconvenience.
